settings = {
	'TOKEN': 'PUT YOUR BOT TOKEN HERE', #	TOKEN
	'NAME BOT': 'PUT YOUR BOT NAME HERE', # BOT NAME
	'ID': 'PUT YOUR BOT ID HERE', # BOT ID
	'PREFIX': ';', # PREFIX
	'OWNER':'PUT YOUR BOT OWNER USERNAME' ',    # OWNER USERNAME
	'OWNER NAME':'PUT YOUR BOT OWNER NAME' # OWNER NAME
}
